config/routes.rb
Ticketee::Application.routes.draw do
  resources :files

  devise_for :users, :controllers => { :registrations => "registrations" }

  put '/admin/users/:user_id/permissions',
  :to => 'admin/permissions#update',
  :as => :update_user_permissions

  get '/awaiting_confirmation',
  :to => "users#confirmation",
  :as => 'confirm_user'

  namespace :admin do
    root :to => "base#index"
    resources :states do
      member do
        get :make_default
      end
    end
    resources :users do
      resources :permissions
    end
  end

  root :to => 'projects#index'

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, presence: true
  has_many :tickets, :dependent => :delete_all

  has_many :permissions, :as => :thing 

  def self.viewable_by(user)
    joins(:permissions).where(:permissions => { :action => "view",
                                :user_id => user.id })
  end

  def self.for(user)
    user.admin? ? Project : Project.viewable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [:show,
                                         :edit,
                                         :update,
                                         :destroy]

  def index
    @projects = Project.for(current_user).all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      redirect_to @project, notice: "Project has been created."
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end
  
  def show
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project]) 
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

private
  def find_project
    @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
      " for could not be found."
    redirect_to projects_path
  end



end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %> 
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li> <%=  link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form"  %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<h2><%= @project.name %></h2>

<% if is_admin?  %>

  <%= link_to "Edit Project", edit_project_path(@project)  %> | 

  <%= link_to "Delete Project", project_path(@project), :method => :delete,
      :confirm => "Are you sure you want to delete this project?" %> |

<% end %>


<% authorized?("create tickets".to_sym, @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
      <li>
        <%= render ticket.state if ticket.state %>
        #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
      </li>
  <% end %>
</ul>